name: Sonar Continuous Integration
env:
  DOTNET_VERSION: '8.x'
  SONAR_ORG: 'alexsanderwilsoncc'
  SONAR_PROJECT: 'lab-2025-ii-si784-u1-01-csharp-ChalloCoaquera'

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install SonarScanner
        run: dotnet tool install -g dotnet-sonarscanner

      - name: Run tests and Sonar analysis
        run: |
          dotnet restore
          dotnet sonarscanner begin /k:"${{ env.SONAR_PROJECT }}" /o:"${{ env.SONAR_ORG }}" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml" /d:sonar.qualitygate.wait=true
          dotnet build --no-incremental
          dotnet test --collect:"XPlat Code Coverage;Format=opencover"
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
